version: '2.1'

services:
  darrenbayliss-dev:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/Labs/darrenbayliss-dev
    ports:
      - $SERVER_PORT:$SERVER_PORT
